steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - repo-function-1
  - --runtime=python37
  - --region=us-central1
  - --source=.
  - --trigger-http
